added html code for input for stock ticker, and separate about and pl…
thedataincubator/stockpredict pull request #23
Opened 2018-04-09 21:54 UTC by andreaslowe

…ot pages

2018-04-09 22:21 UTC, ZachGlassman requested changes
Overall great job!  A few notes:

1. Please make sure the version of bokeh is aligned with the version we will be using https://github.com/thedataincubator/stockpredict/pull/21

2. I would like the header and boostrap imports to be broken off into a base template, see http://flask.pocoo.org/docs/0.12/tutorial/templates/ and see how to use blocks.

2018-04-09 22:21 UTC, ZachGlassman commented on stockticker/templates/index.html
> +    <form id='input' method='post' action='/plotpage' >
Make sure the action is correct

2018-04-11 01:32 UTC, ZachGlassman commented
The integration to actually using a stock ticker is now set up, so you are welcome to alter the backend to do that if you wish.

2018-04-11 01:43 UTC, adrianyi requested changes

2018-04-11 01:43 UTC, adrianyi commented on stockticker/templates/plotpage.html
> +    </div>
One of the div is not closed.

2018-04-11 01:43 UTC, adrianyi commented on stockticker/templates/index.html
> +    <form id='input' method='post' action='/plotpage' >
Just adding on... this could work, but without catching /plotpage route in stockticker.py, this would return 404.
Another option is to stay on same page, but deal with GET and POST requests separately.

2018-04-24 03:26 UTC, ZachGlassman commented
@andreaslowe This branch is going stale, I am going to close the PR, please open a new one with your changes.

2018-04-25 20:21 UTC, closed without merging